defaults:
    - standart_gnn

mlp_config: {
    layers: [
        {
            out_size: 256,
            dropout: 0.0,
            act_func: "LeakyReLU",
            act_func_params: {negative_slope: 0.2},
        },
        {
            out_size: 32,
            dropout: 0.0,
            act_func: "LeakyReLU",
            act_func_params: {negative_slope: 0.2},
        },
    ]
}