# see config.py for the defaults
hydra:
    job:
        chdir: True
    run:
        dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

defaults:  # the last wins
    - base_config
    - _self_

dataset: {}
train: {}
model: {}
